// This file is generated by Convex.
// Run `npx convex dev` to regenerate.

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";

import type * as auth from "../auth.js";
import type * as games from "../games.js";
import type * as queries from "../queries.js";

declare const fullApi: ApiFromModules<{
  auth: typeof auth;
  games: typeof games;
  queries: typeof queries;
}>;

export type Mounts = {};

export declare const api: FilterApi<typeof fullApi, Mounts>;
export declare const internal: FilterApi<typeof fullApi, Mounts>;

export declare const components: {};
