// This file is generated by Convex.
// Run `npx convex dev` to regenerate.

// Stub implementation for build purposes
export const api = {
  auth: {
    signIn: null,
    signOut: null,
  },
  games: {
    createGame: null,
    updateGame: null,
    deleteGame: null,
  },
  queries: {
    listGames: null,
    getGame: null,
    getLeaderboard: null,
  },
};

export const internal = {};
export const components = {};
